# Generated by Django 4.1.6 on 2023-05-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userbankaccount_age_userbankaccount_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='district',
            field=models.CharField(default='kollom', max_length=200),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='materials',
            field=models.CharField(default='debit card', max_length=200),
        ),
        migrations.AddField(
            model_name='userbankaccount',
            name='phone_number',
            field=models.IntegerField(default='8943233657'),
        ),
    ]
